name = input("Enter your name: ")
student_id = input("Enter your student ID: ")
department = input("Enter your department: ")
year = input("Enter your year: ")
university = input("Enter your university: ")
phone = input("Enter your phone number: ")

print("+--------------------------------+")
print("|       STUDENT ID CARD          |")
print("+--------------------------------+")
print("| Name:", name)
print("| ID:", student_id)
print("| Department:", department)
print("| Year:", year)
print("| University:", university)
print("| Phone:", phone)
print("+--------------------------------+")